name: mihaita
security:
  basic:
    enabled: false # turn off securing our application endpoints
  user:
    name: mihaita
    password: a
    role:
      - ADMIN
management:
  security:
    enabled: false # turn off securing the actuator endpoints