name: mihaita
security:
  basic:
    enabled: false
  user:
    name: mihaita
    password: a
    role:
      - ADMIN
management:
  security:
    enabled: false
logging:
  level:
    io:
      pivotal: DEBUG
quoteServiceURL: http://quote-service-dev.cfapps.io/quote